# Site settings
title: Pi Kappa Phi Northeastern  
email: your-email@domain.com
url: ""
baseurl: "hughferg.github.io/pikapp-site-theme"
description: "Ha haaaaa, what's crackin"
keywords: "your keywords, separated by commas"
skills: "Exceptional Leaders, Uncommon Opportunities"
meta_author: Ferguson Hugh

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 005596 #80B3FF
  primary-rgb: "0, 85, 150" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Joesph Aoun 
  location: Location
  social: Lorem Ipsum
  credits: South text 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: instagram
    url: http://instagram.com
  - title: facebook
    url:
  - title: github
    url: http://github.com/hughferg

# Postal address (add as many lines as necessary)
address:
  - line: Northeastern University, Kappa Phi Chapter 
  - line: Boston, MA

# Credits content
credits: 'These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided.'

# Build settings
markdown: kramdown
permalink: pretty