# Site settings
title: Pi Kappa Phi Northeastern 
email: hughferguson25@gmail.com
baseurl: ""
url: "pikappnu.org"
description: "The official website of Pi Kappa Phi at Northeastern University"
keywords: "your keywords, separated by commas"
skills: "Exceptional Leaders, Uncommon Opportunities"
meta_author: Ferguson Hugh

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 005596 #80B3FF
  primary-rgb: "0, 85, 150" #"128,179,255"
  secondary: E7A614 #FD6E8A
  secondary-dark: 005596 

# Footer settings
footer:
  copyright: Pi Kappa Phi, Kappa Chi Chapter 
  location: 
  social: Social

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  - title: instagram
    url: https://www.instagram.com/northeasternpikapp/
  - title: facebook
    url: https://www.facebook.com/pikappaphinu/
  - title: linkedin
    url: https://linkedin.com/
  # - title: github
  #   url: http://github.com/hughferg

# Postal address (add as many lines as necessary)
address:
  - line: Northeastern University, Kappa Phi Chapter 
  - line: Boston, MA

# Credits content
credits: 

# Build settings
markdown: kramdown
permalink: pretty